version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
    volumes:
      - ./resources/subscription_dump.sql:/docker-entrypoint-initdb.d/subscription_dump.sql
    networks:
      - my-proxy-net
  middleware:
    build: .
    expose:
      - "9092"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network

